--1
SELECT *FROM ANGAJATI
WHERE SALARIUL BETWEEN 8000 AND 10000;

--2
SELECT *FROM ANGAJATI
WHERE FUNCTIE = 'SA_REP';

--3
SELECT *FROM ANGAJATI
WHERE FUNCTIE = 'SA_REP' OR FUNCTIE LIKE '%ACCOUNT%';

--4
SELECT *FROM ANG2
WHERE DEP_ID IN (
    SELECT DEP_ID 
    FROM ANG2 
    WHERE NUME = 'Smith'
);

--5
SELECT *
FROM PRODUSE
WHERE PRET_LISTA = (
    SELECT MIN(PRET_LISTA)
    FROM PRODUSE
);

--6
SELECT *FROM ANGAJATI
WHERE SUBSTR(EMAIL, 2, 1) IN ('A', 'B', 'C');

--7
SELECT *FROM ANGAJATI
WHERE TELEFON LIKE '%.123.%';

--8
SELECT *FROM ANGAJATI
WHERE DATA_ANGAJARII < TO_DATE('01-01-2000', 'DD-MM-YYYY');

--9
SELECT * FROM ANGAJATI
WHERE DATA_ANGAJARII BETWEEN TO_DATE('01-01-2000', 'DD-MM-YYYY') AND TO_DATE('31-01-2000', 'DD-MM-YYYY');

--10
ALTER TABLE ANGAJATI 
ADD (ID_DEPARTAMENT NUMBER(4));
UPDATE ANGAJATI SET ID_DEPARTAMENT = 60;
SELECT A.NUME, A.SALARIUL, A.FUNCTIE, D.DENUMIRE_DEPARTAMENT
FROM ANGAJATI A
JOIN DEPARTAMENTE D ON A.ID_DEPARTAMENT = D.ID_DEPARTAMENT
WHERE D.DENUMIRE_DEPARTAMENT = 'IT';

--11
SELECT A.NUME, A.SALARIUL, A.FUNCTIE, D.DENUMIRE_DEPARTAMENT
FROM ANGAJATI A
RIGHT OUTER JOIN DEPARTAMENTE D ON A.ID_DEPARTAMENT = D.ID_DEPARTAMENT
WHERE D.DENUMIRE_DEPARTAMENT LIKE '%IT%';

--12
SELECT C.ID_COMANDA, C.DATA, C.MODALITATE, A.NUME, A.PRENUME
FROM COMENZI C
LEFT JOIN ANGAJATI A ON C.ID_ANGAJAT = A.ANGAJAT_ID;

--13
SELECT P.NUME_PRODUS, P.PRET_LISTA
FROM PRODUSE P
LEFT JOIN RAND_COMENZI R ON P.PRODUS_ID = R.ID_PRODUS;

--14
SELECT A.NUME, A.SALARIUL, A.DATA_ANGAJARII, D.DENUMIRE_DEPARTAMENT
FROM ANGAJATI A
JOIN DEPARTAMENTE D ON A.ID_DEPARTAMENT = D.ID_DEPARTAMENT
WHERE D.DENUMIRE_DEPARTAMENT LIKE '%Sales%' 
ORDER BY A.SALARIUL ASC, A.DATA_ANGAJARII DESC;

--15
ALTER TABLE SALARIATI
ADD (ID_DEPARTAMENT NUMBER(4));
UPDATE SALARIATI
SET ID_DEPARTAMENT = 80
WHERE COMISION IS NOT NULL;
SELECT S.NUME, S.FUNCTIE, S.COMISION, D.DENUMIRE_DEPARTAMENT
FROM SALARIATI S
JOIN DEPARTAMENTE D ON S.ID_DEPARTAMENT = D.ID_DEPARTAMENT
WHERE S.COMISION IS NOT NULL;